### ISSUE TITLE
Set-Location

### ISSUE THREAD

**Issue by Barleyologist** [KlausBilger/SCCM_Check_DP_Libary#1]
The write-log function fails if PS is set to my ConfigMgr location,  I needed to set my location to C:\ for write-log to work.

**Comment by KlausBilger** [comment]
hi

thank you for reporting.
I am not sure if I understood the question or rather the problem from you correctly.
The script uses the same directory as the script itself to create the log file.
A current time stamp is inserted so that the log file is not overwritten.

Code snip
$ LogFile = $ LogFile + "_" + (Get-Date format "yyyy_MM_dd_HH_MM") + ".log"
[string] $ global: scriptName = $ MyInvocation.MyCommand.Name.Replace (". ps1", "") + "_" + $ ((Get-Date -format "yyyy_mm_dd")) + ".log";
[string] $ global: LOG_FILE = $ PSScriptRoot + "\" + $ global: scriptName

**Comment by KlausBilger** [comment]
if necessary, you can change the storage location at any time.

all you have to do is enter the desired location in line 63.


By the way ..
Please do not use the SCCM drive. The file system does not exist here to save the log file.
Make sure the PsDrive provider is FileSystem, or if for some reason you need the PS Drive provider's CMSite then you should really change the location on line 62. I hope this will help you.

If not, please send me a private message

Klaus
